name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: What went wrong?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How do we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: e.g., v1.0.0
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      placeholder: |
        - OS: [e.g., Ubuntu 20.04, Windows 10, macOS 12]
        - Python version: [e.g., 3.9.6]
        - Package versions: [e.g., pandas 1.5.0, numpy 1.21.0]
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste error logs here (if any).
      render: shell
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Screenshots, additional details, etc. 